version: '3.1'
services:
  stats:
    build: ./stats/service
    image: service_image
    container_name: service_container
    ports:
      - "9090:9090"
    depends_on:
      - stats_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats_db:5432/postgres

  stats_db:
    image: postgres:14-alpine
    container_name: stats_db_container
    ports:
      - "5458:5433"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres

  ewm_service:
    build: ./ewm-service
    image: ewm_service_image
    container_name: ewm_service_container
    ports:
      - "8080:8080"

