version: '3.1'
services:
  stats:
    build: ./stats/service
    image: service_image
    ports:
      - "9090:9090"
    depends_on:
      - stats_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats_db:5432/postgres

  stats_db:
    image: postgres:14-alpine
    container_name: stats_db_container
    ports:
      - "5458:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres

  ewm_service:
    build: ./ewm-service
    image: ewm_service_image
    container_name: ewm_service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm_db
      - stats
    environment:
      - STATS_SERVICE_URL=http://stats:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm_db:5432/postgres

  ewm_db:
    image: postgres:14-alpine
    container_name: ewm_db_container
    ports:
      - "5460:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres

