DROP table if exists endpoints-hits;

CREATE TABLE IF NOT EXISTS endpoints-hits
(
     id BIGINT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
     app VARCHAR NOT NULL,
     uri VARCHAR NOT NULL,
     ip VARCHAR NOT NULL,
     creation-time TIMESTAMP WITHOUT TIME ZONE
    );

CREATE TABLE IF NOT EXISTS view-stats
(
     app VARCHAR NOT NULL PRIMARY KEY,
     uri VARCHAR NOT NULL UNIQUE,
     hits  BIGINT
    );